stages:
  - staging
  - production

staging-state:
  stage: staging
  script:
    - gem install dpl
    - dpl --provider=heroku --app=staging-monggovest --api-key=1684e917-0abc-40e2-8ba0-3f722529b86a
    - curl -s -X POST https://api.telegram.org/bot753819662:AAGNPS9tTHw_BWSB9nEy2FVMa45RjpQjbww/sendMessage -d chat_id=-1001311231318 -d text="[Staging-Monggovest-BOT] Deploy Done | Deployed by $GITLAB_USER_NAME | ${CI_COMMIT_SHA:0:8} | $CI_COMMIT_TITLE"  

  only:
    - develop

production-state:
  stage: production
  script:
    - gem install dpl
    - dpl --provider=heroku --app=monggovest-batam --api-key=1684e917-0abc-40e2-8ba0-3f722529b86a
    - curl -s -X POST https://api.telegram.org/bot753819662:AAGNPS9tTHw_BWSB9nEy2FVMa45RjpQjbww/sendMessage -d chat_id=-1001311231318 -d text="[Production-Monggovest-BOT] Deploy Done | Deployed by $GITLAB_USER_NAME | ${CI_COMMIT_SHA:0:8} | $CI_COMMIT_TITLE"  
  only:
    - master
